const jwt = require("jsonwebtoken");


//decode , verify , generate
const value ={
    name: "harkirat",
    accountNumber: 123123123

}

//jwt
//fn to generate is sign
const token = jwt.sign(value, "secret");
//this token has been generated by secret then secret can only verify the jwt




